#!/bin/bash
set -e  # Exit on error

echo "🚀 Phasor V2 Deployment Script"
echo "================================"
echo ""

# Configuration
RPC_URL="${RPC_URL:-http://127.0.0.1:8545}"
CHAIN_ID="${CHAIN_ID:-143}"
LIBRARY_FILE="packages/periphery/contracts/libraries/UniswapV2Library.sol"
FRONTEND_ENV="packages/phasor-dex/.env.local"

# Step 1: Compile contracts
echo "📦 Step 1: Compiling contracts..."
forge build packages/ --force
echo "✅ Contracts compiled"
echo ""

# Step 2: Calculate INIT_CODE_HASH
echo "🔍 Step 2: Calculating INIT_CODE_HASH..."
INIT_CODE_HASH=$(npx ts-node script/calculateInitHash.ts)
echo "   INIT_CODE_HASH: $INIT_CODE_HASH"
echo ""

# Step 3: Update UniswapV2Library.sol
echo "✏️  Step 3: Updating UniswapV2Library.sol..."

# Check if the file exists
if [ ! -f "$LIBRARY_FILE" ]; then
    echo "❌ Error: $LIBRARY_FILE not found!"
    exit 1
fi

# Use sed to replace the init code hash (works on both macOS and Linux)
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    sed -i '' "s/hex'[0-9a-f]\{64\}' \/\/ init code hash/hex'${INIT_CODE_HASH:2}' \/\/ init code hash/" "$LIBRARY_FILE"
else
    # Linux
    sed -i "s/hex'[0-9a-f]\{64\}' \/\/ init code hash/hex'${INIT_CODE_HASH:2}' \/\/ init code hash/" "$LIBRARY_FILE"
fi

echo "✅ UniswapV2Library.sol updated with new hash"
echo ""

# Step 4: Recompile with updated hash
echo "📦 Step 4: Recompiling with updated hash..."
forge build packages/ --force
echo "✅ Recompiled"
echo ""

# Step 5: Deploy with Cannon
echo "🔨 Step 5: Deploying contracts with Cannon..."
echo "   RPC: $RPC_URL"
echo "   Chain ID: $CHAIN_ID"
echo ""

DEPLOY_OUTPUT=$(npx @usecannon/cli build --rpc-url "$RPC_URL" --chain-id "$CHAIN_ID" --wipe 2>&1)
echo "$DEPLOY_OUTPUT"

# Extract Factory and Router addresses from the output
FACTORY_ADDRESS=$(echo "$DEPLOY_OUTPUT" | grep -A 2 "deploy.UniswapV2Factory" | grep "Contract Address:" | sed 's/.*Contract Address: //' | tr -d ' ')
ROUTER_ADDRESS=$(echo "$DEPLOY_OUTPUT" | grep -A 2 "deploy.UniswapV2Router" | grep "Contract Address:" | sed 's/.*Contract Address: //' | tr -d ' ')
TKN1_ADDRESS=$(echo "$DEPLOY_OUTPUT" | grep -A 2 "deploy.TKN1" | grep "Contract Address:" | sed 's/.*Contract Address: //' | tr -d ' ')
TKN2_ADDRESS=$(echo "$DEPLOY_OUTPUT" | grep -A 2 "deploy.TKN2" | grep "Contract Address:" | sed 's/.*Contract Address: //' | tr -d ' ')

if [ -z "$FACTORY_ADDRESS" ] || [ -z "$ROUTER_ADDRESS" ]; then
    echo "❌ Error: Could not extract contract addresses from deployment output"
    exit 1
fi

# Get current block number for subgraph start block
START_BLOCK=$(cast block-number --rpc-url "$RPC_URL")

echo ""
echo "✅ Deployment complete!"
echo "   Factory: $FACTORY_ADDRESS"
echo "   Router: $ROUTER_ADDRESS"
echo "   TKN1: $TKN1_ADDRESS"
echo "   TKN2: $TKN2_ADDRESS"
echo ""

# Step 6: Update frontend .env.local
echo "⚙️  Step 6: Updating frontend environment variables..."

# Create .env.local file
cat > "$FRONTEND_ENV" << EOF
# Uniswap V2 Contract Addresses
# Auto-generated by deploy.sh - $(date)
NEXT_PUBLIC_DEFAULT_FACTORY_ADDRESS=$FACTORY_ADDRESS
NEXT_PUBLIC_DEFAULT_ROUTER_ADDRESS=$ROUTER_ADDRESS

NEXT_PUBLIC_DEFAULT_TKN1_ADDRESS=$TKN1_ADDRESS
NEXT_PUBLIC_DEFAULT_TKN2_ADDRESS=$TKN2_ADDRESS

# Network Configuration
NEXT_PUBLIC_DEFAULT_RPC_URL=$RPC_URL
NEXT_PUBLIC_DEFAULT_CHAIN_ID=$CHAIN_ID

# Subgraph Configuration
NEXT_PUBLIC_SUBGRAPH_URL=http://localhost:8000/subgraphs/name/phasor/phasor-v2
EOF

echo "✅ Frontend .env.local updated"
echo ""

# Step 7: Update tokenlist.json with new addresses
echo "📝 Step 7: Updating tokenlist.json..."

TOKENLIST_FILE="packages/phasor-dex/public/tokenlist.json"

# Use Node.js to update the JSON file properly
node << EONODE
const fs = require('fs');
const tokenList = JSON.parse(fs.readFileSync('$TOKENLIST_FILE', 'utf8'));

// Update timestamp
tokenList.timestamp = new Date().toISOString();

// Update TKN1 and TKN2 addresses
tokenList.tokens = tokenList.tokens.map(token => {
  if (token.symbol === 'TKN1') {
    return { ...token, address: '$TKN1_ADDRESS' };
  }
  if (token.symbol === 'TKN2') {
    return { ...token, address: '$TKN2_ADDRESS' };
  }
  return token;
});

fs.writeFileSync('$TOKENLIST_FILE', JSON.stringify(tokenList, null, 2));
console.log('✅ Token list updated');
EONODE

echo ""

# Step 8: Update subgraph configuration
echo "📊 Step 8: Updating subgraph configuration..."

SUBGRAPH_CONFIG="packages/v2-subgraph/config/monad/config.json"

if [ -f "$SUBGRAPH_CONFIG" ]; then
    cat > "$SUBGRAPH_CONFIG" << EOF
{
  "network": "monad",
  "factory": "$FACTORY_ADDRESS",
  "startblock": "$START_BLOCK"
}
EOF
    echo "✅ Subgraph configuration updated"
    echo "   Factory: $FACTORY_ADDRESS"
    echo "   Start Block: $START_BLOCK"
else
    echo "⚠️  Warning: Subgraph config file not found at $SUBGRAPH_CONFIG"
fi

echo ""

# Step 9: Summary
echo "🎉 Deployment Complete!"
echo "================================"
echo ""
echo "Contract Addresses:"
echo "  Factory: $FACTORY_ADDRESS"
echo "  Router:  $ROUTER_ADDRESS"
echo "  TKN1:    $TKN1_ADDRESS"
echo "  TKN2:    $TKN2_ADDRESS"
echo ""
echo "INIT_CODE_HASH: $INIT_CODE_HASH"
echo ""
echo "Frontend configuration: $FRONTEND_ENV"
echo "Subgraph configuration: $SUBGRAPH_CONFIG"
echo ""
echo "Next steps:"
echo "  1. Build and deploy the subgraph:"
echo "     cd packages/v2-subgraph"
echo "     yarn build --network monad --subgraph-type v2"
echo "     ./scripts/deploy-local.sh"
echo "  2. Restart your frontend dev server to pick up the new env vars"
echo "  3. Make sure your wallet is connected to $RPC_URL (Chain ID: $CHAIN_ID)"
echo "  4. Use account 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 for testing"
echo ""
